[video_stream.camera]
height = 480
width = 640
framerate_n = 16
framerate_d = 1
format = "YUY2"

[video_stream.detection]
nats_server_uri = "nats://127.0.0.1:4223"
label_file = "/usr/share/printnanny/model/labels.txt"
model_file = "/usr/share/printnanny/model/model.tflite"
nms_threshold = 70
tensor_batch_size = 40
tensor_framerate = 2
tensor_height = 320
tensor_width = 320
overlay = true
graphs = true

[video_stream.hls]
segments = "/var/run/printnanny-hls/segment%05d.ts"
playlist = "/var/run/printnanny-hls/playlist.m3u8"
playlist_root = "/printnanny-hls/"
enabled = true

[video_stream.recording]
path = "/home/printnanny/.local/share/printnanny/video"
auto_start = true
cloud_sync = true

[video_stream.rtp]
video_udp_port = 20001
overlay_udp_port = 20002

[video_stream.snapshot]
path = "/var/run/printnanny-snapshot/snapshot-%d.jpg"
enabled = true

[cloud]
api_base_path = "https://printnanny.ai"

[git]
path = "/home/printnanny/.config/printnanny/vcs"
remote = "https://github.com/bitsy-ai/printnanny-settings.git"
email = "robots@printnanny.ai"
name = "PrintNanny"
default_branch = "main"

[paths]
snapshot_dir = "/var/run/printnanny-snapshot"
state_dir = "/home/printnanny/.local/share/printnanny"
log_dir = "/var/log/printnanny"
run_dir = "/var/run/printnanny"
issue_txt = "/etc/issue"
os_release = "/etc/os-release"
