[cam]
preview = false
nats_server_uri = "nats://127.0.0.1:4223"
overlay_udp_port = 20002
video_udp_port = 20001
video_height = 480
video_width = 640
video_framerate = 24
hls_segments = "/var/run/printnanny-hls/segment%05d.ts"
hls_playlist = "/var/run/printnanny-hls/playlist.m3u8"
hls_playlist_root = "/printnanny-hls/"

[cam.tflite_model]
label_file = "/usr/share/printnanny/model/labels.txt"
model_file = "/usr/share/printnanny/model/model.tflite"
nms_threshold = 66
tensor_batch_size = 40
tensor_channels = 3
tensor_height = 320
tensor_width = 320
tensor_framerate = 3

[cam.video_src]
src_type = "csi"
index = 0
device_name = "/base/soc/i2c0mux/i2c@1/imx219@10"
label = "imx219"

[git]
remote = "https://github.com/bitsy-ai/printnanny-settings.git"
email = "robots@printnanny.ai"
name = "PrintNanny"
default_branch = "main"

[paths]
state_dir = "/home/printnanny/.local/share/printnanny"
settings_dir = "/home/printnanny/.config/printnanny/vcs"
log_dir = "/var/log/printnanny"
run_dir = "/var/run/printnanny"
issue_txt = "/etc/issue"
os_release = "/etc/os-release"

[klipper]
enabled = false
install_dir = "/home/printnanny/.klipper"
settings_file = "/home/printnanny/.config/printnanny/vcs/klipper/printer.cfg"
settings_format = "ini"
venv = "/home/printnanny/klipper-venv"

[mainsail]
enabled = false
install_dir = "/var/www/mainsail"

[moonraker]
enabled = false
install_dir = "/home/printnanny/.moonraker"
settings_file = "/home/printnanny/.config/printnanny/vcs/moonraker/moonraker.conf"
settings_format = "ini"
venv = "/home/printnanny/moonraker-venv"

[octoprint]
enabled = true
install_dir = "/home/printnanny/.octoprint"
settings_file = "/home/printnanny/.config/printnanny/vcs/octoprint/octoprint.yaml"
settings_format = "yaml"
